/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Globe: typeof import('./src/components/Globe.vue')['default']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardSection: typeof import('quasar')['QCardSection']
    QDrawer: typeof import('quasar')['QDrawer']
    QItem: typeof import('quasar')['QItem']
    QItemSection: typeof import('quasar')['QItemSection']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QTab: typeof import('quasar')['QTab']
    QTabs: typeof import('quasar')['QTabs']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
